<?php

namespace App\Filament\Admin\Resources\CourceResource\Pages;

use App\Filament\Admin\Resources\CourceResource;
use Filament\Actions;


use Filament\Infolists\Components\Actions\Action;
use Filament\Infolists\Components\Section;
use Filament\Infolists\Components\TextEntry;
use Filament\Infolists\Infolist;
use Filament\Resources\Pages\ViewRecord;
use Filament\Support\Enums\FontWeight;
use Filament\Tables\Columns\TextColumn;

class ViewCource extends ViewRecord
{
    protected static string $resource = CourceResource::class;

    public function infolist(Infolist $infolist): Infolist
    {
        return $infolist->schema([
            Section::make('Content')->schema([
                TextEntry::make('title')->weight(FontWeight::Bold),
                TextEntry::make('description')->weight(FontWeight::Bold),
                TextEntry::make('price')->weight(FontWeight::Bold),
            ])
        ]); // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\EditAction::make(),
        ];
    }
}
